sudo: required
dist: trusty
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
before_deploy:
  - npm run storybook:build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN # Set in travis-ci.org dashboard
  keep-history: true
  local-dir: docs/dist # Set the builded dist as the folder to deploy
  on:
    branch: master
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
