language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
  - '6'
  - '4'
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
before_deploy:
  - npm run storybook:build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs/dist # Set the builded dist as the folder to deploy
  on:
    branch: master
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
